name: Release

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: googleapis/release-please-action@v5
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
